import React, { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Header } from '@/components/shared/Header';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';
import { Alert, AlertDescription } from '@/components/ui/alert';
import {
  ChevronRight,
  FileText,
  Download,
  Calendar,
  Clock,
  Upload,
  CheckCircle2,
  XCircle,
  Info,
  User,
  AlertTriangle,
} from 'lucide-react';
import { toast } from 'sonner';

const caseData = {
  id: 1,
  caseNumber: 'DBE-EC-02025-004',
  caseName: 'Smith vs. Department of Natural Resources',
  caseType: 'Abandoned Well',
  department: 'Abandoned well',
  parties: 'John Smith, Department of Natural Resources',
  aljName: 'Hon. Patricia Martinez',
  recommendedDate: '11/25/2024',
  deadline: '12/15/2024',
  daysRemaining: 6,
  status: 'On Time (6 days remaining)',
  statusColor: 'bg-green-100 text-green-800',
  recommendationOutcome: 'Granted',
  summary: 'The Administrative Law Judge recommends granting the petitioner\'s request for remediation assistance based on the evidence presented during the hearing. The respondent failed to demonstrate compliance with environmental regulations as required under statute.',
};

const recommendedDocuments = [
  {
    id: 1,
    name: 'Recommended Decision Report',
    type: 'System Generated',
    uploadedBy: 'ALJ Patricia Martinez',
    date: '11/25/2024',
  },
];

const activityLog = [
  { date: '11/25/2024 2:30 PM', event: 'Recommended Decision generated by ALJ Patricia Martinez' },
  { date: '11/25/2024 2:35 PM', event: 'Recommended Report & Notification sent to FDM' },
  { date: '11/28/2024 9:15 AM', event: 'FDM opened case for review' },
];

const FinalDecisionDetail: React.FC = () => {
  const navigate = useNavigate();
  const { id } = useParams();
  const [activeTab, setActiveTab] = useState('recommended');
  const [actionChoice, setActionChoice] = useState<'approve' | 'disagree' | null>(null);
  const [approvalComments, setApprovalComments] = useState('');
  const [rejectionJustification, setRejectionJustification] = useState('');
  const [isRulingGenerated, setIsRulingGenerated] = useState(false);
  const [uploadedFile, setUploadedFile] = useState<File | null>(null);
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [fdmStatus, setFdmStatus] = useState<'pending' | 'approved' | 'rejected'>('pending');

  const handleGenerateRuling = () => {
    setIsRulingGenerated(true);
    toast.success('Final Ruling Report generated successfully');
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      if (file.type !== 'application/pdf') {
        toast.error('Only PDF files are allowed');
        return;
      }
      if (file.size > 10 * 1024 * 1024) {
        toast.error('File size must be less than 10 MB');
        return;
      }
      setUploadedFile(file);
      toast.success('File uploaded successfully');
    }
  };

  const handleSubmitDecision = () => {
    if (actionChoice === 'approve') {
      setFdmStatus('approved');
    } else {
      setFdmStatus('rejected');
    }
    setIsSubmitted(true);
    toast.success('Final Administrative Decision recorded');
  };

  const canSubmit = () => {
    if (actionChoice === 'approve') {
      return isRulingGenerated;
    }
    if (actionChoice === 'disagree') {
      return uploadedFile && rejectionJustification.trim().length > 0;
    }
    return false;
  };

  const getStatusBadge = () => {
    switch (fdmStatus) {
      case 'approved':
        return <Badge className="bg-green-100 text-green-800 font-fluent">Approved – Final Ruling Generated</Badge>;
      case 'rejected':
        return <Badge className="bg-orange-100 text-orange-800 font-fluent">Rejected – FDM Ruling Uploaded</Badge>;
      default:
        return <Badge className="bg-yellow-100 text-yellow-800 font-fluent">FDM Pending</Badge>;
    }
  };

  return (
    <div className="min-h-screen bg-gray-100">
      <Header />
      
      <main className="container mx-auto px-6 py-6">
        {/* Breadcrumb */}
        <div className="flex items-center text-sm text-muted-foreground mb-4 font-fluent">
          <span 
            className="hover:text-primary cursor-pointer"
            onClick={() => navigate('/portal')}
          >
            Dashboard
          </span>
          <ChevronRight className="h-4 w-4 mx-2" />
          <span 
            className="hover:text-primary cursor-pointer"
            onClick={() => navigate('/fdm')}
          >
            Final Decisions
          </span>
          <ChevronRight className="h-4 w-4 mx-2" />
          <span className="text-foreground font-medium">{caseData.caseNumber}</span>
        </div>

        {/* Top Band */}
        <div className="bg-[#1a365d] rounded-lg p-4 mb-6 flex items-center justify-between">
          <h1 className="text-xl font-semibold text-white font-fluent">
            Final Decision – {caseData.caseName}
          </h1>
          <Card className="bg-white/10 border-white/20">
            <CardContent className="p-3 flex items-center gap-4">
              <div className="text-white font-fluent">
                <div className="text-sm opacity-80">Case: {caseData.caseNumber}</div>
                <div className="text-sm opacity-80">{caseData.caseType}</div>
              </div>
              <div className="border-l border-white/30 pl-4 flex flex-col gap-2">
                <div className="flex items-center gap-2">
                  <Calendar className="h-4 w-4 text-white/80" />
                  <div className="text-white font-fluent text-sm">
                    <div>Deadline: {caseData.deadline}</div>
                  </div>
                </div>
                <Badge className={`${caseData.statusColor} font-fluent w-fit`}>
                  {caseData.status}
                </Badge>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Tabs */}
        <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
          <TabsList className="bg-white border border-gray-200 mb-4">
            <TabsTrigger 
              value="recommended" 
              className="font-fluent data-[state=active]:bg-blue-600 data-[state=active]:text-white"
            >
              Recommended Decision
            </TabsTrigger>
            <TabsTrigger 
              value="final" 
              className="font-fluent data-[state=active]:bg-blue-600 data-[state=active]:text-white"
            >
              Final Decision
            </TabsTrigger>
            <TabsTrigger 
              value="activity" 
              className="font-fluent data-[state=active]:bg-blue-600 data-[state=active]:text-white"
            >
              Activity Log
            </TabsTrigger>
          </TabsList>

          {/* Tab 1: Recommended Decision */}
          <TabsContent value="recommended">
            <div className="grid grid-cols-2 gap-6">
              {/* Left Card */}
              <Card className="border border-gray-200 shadow-sm">
                <CardHeader className="border-b border-gray-200 bg-gray-50">
                  <CardTitle className="text-lg font-fluent text-[#1a365d]">
                    Recommended Decision Details
                  </CardTitle>
                </CardHeader>
                <CardContent className="p-4 space-y-4">
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="text-sm font-medium text-muted-foreground font-fluent">ALJ Name</label>
                      <div className="flex items-center gap-2 mt-1">
                        <User className="h-4 w-4 text-muted-foreground" />
                        <span className="font-fluent">{caseData.aljName}</span>
                      </div>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-muted-foreground font-fluent">Recommended Decision Date</label>
                      <div className="flex items-center gap-2 mt-1">
                        <Calendar className="h-4 w-4 text-muted-foreground" />
                        <span className="font-fluent">{caseData.recommendedDate}</span>
                      </div>
                    </div>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-muted-foreground font-fluent">Summary</label>
                    <p className="mt-1 text-sm font-fluent text-gray-700">{caseData.summary}</p>
                  </div>
                </CardContent>
              </Card>

              {/* Right Card */}
              <Card className="border border-gray-200 shadow-sm">
                <CardHeader className="border-b border-gray-200 bg-gray-50">
                  <CardTitle className="text-lg font-fluent text-[#1a365d]">
                    Recommended Documents
                  </CardTitle>
                </CardHeader>
                <CardContent className="p-4">
                  <div className="space-y-3">
                    {recommendedDocuments.map((doc) => (
                      <div 
                        key={doc.id}
                        className="flex items-center justify-between p-3 bg-gray-50 rounded-lg border border-gray-200"
                      >
                        <div className="flex items-center gap-3">
                          <FileText className="h-5 w-5 text-blue-600" />
                          <div>
                            <div className="font-medium font-fluent">{doc.name}</div>
                            <div className="text-xs text-muted-foreground font-fluent">
                              {doc.type} • {doc.uploadedBy} • {doc.date}
                            </div>
                          </div>
                        </div>
                        <Button variant="ghost" size="sm">
                          <Download className="h-4 w-4 text-blue-600" />
                        </Button>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            </div>

            {/* Info Banner */}
            <Alert className="mt-6 bg-blue-50 border-blue-200">
              <Info className="h-4 w-4 text-blue-600" />
              <AlertDescription className="font-fluent text-blue-800">
                This recommended decision has been routed to you as Final Decision Maker. Approve it to generate a Final Ruling Report, or upload your own final ruling if you disagree.
              </AlertDescription>
            </Alert>
          </TabsContent>

          {/* Tab 2: Final Decision */}
          <TabsContent value="final">
            {isSubmitted ? (
              <Alert className="bg-green-50 border-green-200">
                <CheckCircle2 className="h-5 w-5 text-green-600" />
                <AlertDescription className="font-fluent text-green-800 text-base">
                  Final Administrative Decision recorded. The system has {actionChoice === 'approve' ? 'generated' : 'registered'} the Final Ruling Report and sent it to the appropriate external parties.
                </AlertDescription>
              </Alert>
            ) : (
              <div className="grid grid-cols-2 gap-6">
                {/* Left Card */}
                <Card className="border border-gray-200 shadow-sm">
                  <CardHeader className="border-b border-gray-200 bg-gray-50">
                    <CardTitle className="text-lg font-fluent text-[#1a365d]">
                      Final Decision Summary
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="p-4 space-y-4">
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <label className="text-sm font-medium text-muted-foreground font-fluent">Case ID</label>
                        <div className="font-fluent mt-1">{caseData.caseNumber}</div>
                      </div>
                      <div>
                        <label className="text-sm font-medium text-muted-foreground font-fluent">Case Name</label>
                        <div className="font-fluent mt-1 text-sm">{caseData.caseName}</div>
                      </div>
                    </div>
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <label className="text-sm font-medium text-muted-foreground font-fluent">Department</label>
                        <div className="font-fluent mt-1">{caseData.department}</div>
                      </div>
                      <div>
                        <label className="text-sm font-medium text-muted-foreground font-fluent">Parties</label>
                        <div className="font-fluent mt-1 text-sm">{caseData.parties}</div>
                      </div>
                    </div>
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <label className="text-sm font-medium text-muted-foreground font-fluent">FDM Deadline</label>
                        <div className="flex items-center gap-2 mt-1">
                          <Calendar className="h-4 w-4 text-muted-foreground" />
                          <span className="font-fluent">{caseData.deadline}</span>
                        </div>
                      </div>
                      <div>
                        <label className="text-sm font-medium text-muted-foreground font-fluent">Days Remaining</label>
                        <div className="flex items-center gap-2 mt-1">
                          <Clock className="h-4 w-4 text-muted-foreground" />
                          <span className="font-fluent">{caseData.daysRemaining} days</span>
                          
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </Card>

                {/* Right Card */}
                <Card className="border border-gray-200 shadow-sm">
                  <CardHeader className="border-b border-gray-200 bg-gray-50">
                    <div className="flex items-center justify-between">
                      <CardTitle className="text-lg font-fluent text-[#1a365d]">
                        Final Decision Maker Action
                      </CardTitle>
                      {getStatusBadge()}
                    </div>
                  </CardHeader>
                  <CardContent className="p-4 space-y-6">
                    {/* Action Choice */}
                    <div className="space-y-3">
                      <label className="text-sm font-medium text-muted-foreground font-fluent">Choose Your Action</label>
                      <div className="grid grid-cols-2 gap-3">
                        <Button
                          variant={actionChoice === 'approve' ? 'default' : 'outline'}
                          className={`h-16 flex flex-col items-center justify-center gap-1 ${
                            actionChoice === 'approve' ? 'bg-green-600 hover:bg-green-700' : ''
                          }`}
                          onClick={() => {
                            setActionChoice('approve');
                            setUploadedFile(null);
                            setRejectionJustification('');
                          }}
                        >
                          <CheckCircle2 className="h-5 w-5" />
                          <span className="font-fluent text-sm">Approve Recommended Decision</span>
                        </Button>
                        <Button
                          variant={actionChoice === 'disagree' ? 'default' : 'outline'}
                          className={`h-16 flex flex-col items-center justify-center gap-1 ${
                            actionChoice === 'disagree' ? 'bg-orange-600 hover:bg-orange-700' : ''
                          }`}
                          onClick={() => {
                            setActionChoice('disagree');
                            setIsRulingGenerated(false);
                            setApprovalComments('');
                          }}
                        >
                          <XCircle className="h-5 w-5" />
                          <span className="font-fluent text-sm">Disagree / Upload Own Ruling</span>
                        </Button>
                      </div>
                    </div>

                    {/* Approve Section */}
                    {actionChoice === 'approve' && (
                      <div className="space-y-4 p-4 bg-green-50 rounded-lg border border-green-200">
                        <p className="text-sm font-fluent text-green-800">
                          Approving will automatically generate a Final Ruling Report based on the ALJ's recommendation.
                        </p>
                        <div>
                          <label className="text-sm font-medium text-muted-foreground font-fluent">
                            Optional comments to accompany your approval
                          </label>
                          <Textarea
                            value={approvalComments}
                            onChange={(e) => setApprovalComments(e.target.value)}
                            placeholder="Enter any additional comments..."
                            className="mt-2 font-fluent"
                            rows={3}
                          />
                        </div>
                        {!isRulingGenerated ? (
                          <Button 
                            className="bg-green-600 hover:bg-green-700 font-fluent"
                            onClick={handleGenerateRuling}
                          >
                            Generate Final Ruling Report
                          </Button>
                        ) : (
                          <div className="space-y-3">
                            <div className="flex items-center justify-between p-3 bg-white rounded-lg border border-green-300">
                              <div className="flex items-center gap-3">
                                <FileText className="h-5 w-5 text-green-600" />
                                <div>
                                  <div className="font-medium font-fluent">Final Ruling Report</div>
                                  <div className="text-xs text-muted-foreground font-fluent">
                                    System Generated • Just now
                                  </div>
                                </div>
                              </div>
                              <Button variant="ghost" size="sm">
                                <Download className="h-4 w-4 text-green-600" />
                              </Button>
                            </div>
                            <Button className="bg-blue-600 hover:bg-blue-700 font-fluent">
                              Sign & Send
                            </Button>
                          </div>
                        )}
                      </div>
                    )}

                    {/* Disagree Section */}
                    {actionChoice === 'disagree' && (
                      <div className="space-y-4 p-4 bg-orange-50 rounded-lg border border-orange-200">
                        <div className="flex items-start gap-2">
                          <AlertTriangle className="h-5 w-5 text-orange-600 mt-0.5" />
                          <p className="text-sm font-fluent text-orange-800">
                            Upload your own final ruling PDF. This will replace the ALJ's recommendation as the Final Administrative Decision.
                          </p>
                        </div>
                        
                        {/* Upload Area */}
                        <div 
                          className="border-2 border-dashed border-orange-300 rounded-lg p-6 text-center bg-white cursor-pointer hover:border-orange-400 transition-colors"
                          onClick={() => document.getElementById('file-upload')?.click()}
                        >
                          <Upload className="h-8 w-8 text-orange-400 mx-auto mb-2" />
                          <p className="text-sm font-fluent text-gray-600">
                            Drag and drop files here, or click to browse
                          </p>
                          <p className="text-xs text-muted-foreground font-fluent mt-1">
                            PDF only, max 10 MB
                          </p>
                          <input
                            id="file-upload"
                            type="file"
                            accept=".pdf"
                            className="hidden"
                            onChange={handleFileUpload}
                          />
                        </div>

                        {uploadedFile && (
                          <div className="flex items-center justify-between p-3 bg-white rounded-lg border border-orange-300">
                            <div className="flex items-center gap-3">
                              <FileText className="h-5 w-5 text-orange-600" />
                              <div>
                                <div className="font-medium font-fluent">{uploadedFile.name}</div>
                                <div className="text-xs text-muted-foreground font-fluent">
                                  {(uploadedFile.size / 1024 / 1024).toFixed(2)} MB
                                </div>
                              </div>
                            </div>
                            <Button 
                              variant="ghost" 
                              size="sm"
                              onClick={() => setUploadedFile(null)}
                            >
                              <XCircle className="h-4 w-4 text-red-500" />
                            </Button>
                          </div>
                        )}

                        <div>
                          <label className="text-sm font-medium text-muted-foreground font-fluent">
                            Required justification for rejecting the recommendation *
                          </label>
                          <Textarea
                            value={rejectionJustification}
                            onChange={(e) => setRejectionJustification(e.target.value)}
                            placeholder="Explain why you are disagreeing with the ALJ's recommendation..."
                            className="mt-2 font-fluent"
                            rows={4}
                            required
                          />
                        </div>

                        <Button 
                          className="bg-orange-600 hover:bg-orange-700 font-fluent"
                          disabled={!uploadedFile}
                          onClick={() => toast.success('Final Ruling uploaded and marked as final')}
                        >
                          Upload Final Ruling & Mark as Final
                        </Button>
                      </div>
                    )}

                    {/* Action Buttons */}
                    <div className="flex justify-end gap-3 pt-4 border-t border-gray-200">
                      <Button 
                        variant="outline" 
                        className="font-fluent"
                        onClick={() => navigate('/fdm')}
                      >
                        Cancel
                      </Button>
                      <Button 
                        className="bg-blue-600 hover:bg-blue-700 font-fluent"
                        disabled={!canSubmit()}
                        onClick={handleSubmitDecision}
                      >
                        Submit Final Decision
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              </div>
            )}
          </TabsContent>

          {/* Tab 3: Activity Log */}
          <TabsContent value="activity">
            <Card className="border border-gray-200 shadow-sm">
              <CardHeader className="border-b border-gray-200 bg-gray-50">
                <CardTitle className="text-lg font-fluent text-[#1a365d]">
                  Activity Log
                </CardTitle>
              </CardHeader>
              <CardContent className="p-4">
                <div className="space-y-4">
                  {activityLog.map((item, index) => (
                    <div key={index} className="flex items-start gap-4">
                      <div className="flex flex-col items-center">
                        <div className="w-3 h-3 bg-blue-600 rounded-full" />
                        {index < activityLog.length - 1 && (
                          <div className="w-0.5 h-12 bg-gray-300 mt-1" />
                        )}
                      </div>
                      <div>
                        <div className="text-sm font-medium font-fluent text-gray-700">{item.event}</div>
                        <div className="text-xs text-muted-foreground font-fluent">{item.date}</div>
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </main>
    </div>
  );
};

export default FinalDecisionDetail;
