import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Header } from '@/components/shared/Header';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';
import { Alert, AlertDescription } from '@/components/ui/alert';
import {
  ChevronRight,
  FileText,
  Download,
  Calendar,
  Clock,
  Upload,
  CheckCircle2,
  XCircle,
  Info,
  User,
  AlertTriangle,
  Circle,
} from 'lucide-react';
import { toast } from 'sonner';

// Mock case data
const caseData = {
  id: 1,
  caseNumber: 'DBE-EC-02025-007',
  caseName: 'Johnson vs. Department of Environmental Quality',
  caseType: 'Environmental Compliance',
  department: 'Environmental Quality',
  parties: 'Michael Johnson, Department of Environmental Quality',
  primaryParty: 'Michael Johnson',
  aljName: 'Hon. Patricia Martinez',
  recommendedDate: '12/01/2024',
  deadline: '12/20/2024',
  daysRemaining: 9,
  status: 'FDM Pending',
  statusColor: 'bg-yellow-100 text-yellow-800',
  recommendationOutcome: 'Granted',
  summary: 'The Administrative Law Judge recommends granting the petitioner\'s request for environmental compliance review based on the evidence presented during the hearing. The respondent failed to demonstrate adherence to environmental regulations as required under statute.',
};

// Mock recommended documents
const recommendedDocuments = [
  {
    id: 1,
    name: 'Recommended Decision Report',
    type: 'System Generated',
    uploadedBy: 'ALJ Patricia Martinez',
    date: '12/01/2024',
  },
];

// Mock process log entries
const processLogEntries = [
  { 
    id: 1,
    date: '12/01/2024 2:30 PM', 
    event: 'Recommended Decision issued by ALJ',
    actor: 'ALJ Patricia Martinez',
    status: 'completed'
  },
  { 
    id: 2,
    date: '12/01/2024 2:35 PM', 
    event: 'Recommended Document delivered to FDM',
    actor: 'System',
    status: 'completed'
  },
  { 
    id: 3,
    date: '12/03/2024 9:15 AM', 
    event: 'FDM opened Final Decision tab',
    actor: 'FDM Office',
    status: 'completed'
  },
  { 
    id: 4,
    date: '', 
    event: 'FDM approved or rejected decision',
    actor: '',
    status: 'pending'
  },
  { 
    id: 5,
    date: '', 
    event: 'Final Ruling generated or uploaded',
    actor: '',
    status: 'pending'
  },
  { 
    id: 6,
    date: '', 
    event: 'Final Ruling served to external parties',
    actor: '',
    status: 'pending'
  },
];

const FinalDecisionTest: React.FC = () => {
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState('recommended');
  const [actionChoice, setActionChoice] = useState<'approve' | 'disagree' | null>(null);
  const [approvalComments, setApprovalComments] = useState('');
  const [rejectionJustification, setRejectionJustification] = useState('');
  const [isRulingGenerated, setIsRulingGenerated] = useState(false);
  const [uploadedFile, setUploadedFile] = useState<File | null>(null);
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [fdmStatus, setFdmStatus] = useState<'pending' | 'approved' | 'rejected'>('pending');
  const [processLog, setProcessLog] = useState(processLogEntries);

  const handleGenerateRuling = () => {
    setIsRulingGenerated(true);
    toast.success('Final Ruling Report generated successfully');
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      if (file.type !== 'application/pdf') {
        toast.error('Only PDF files are allowed');
        return;
      }
      if (file.size > 10 * 1024 * 1024) {
        toast.error('File size must be less than 10 MB');
        return;
      }
      setUploadedFile(file);
      toast.success('File uploaded successfully');
    }
  };

  const handleSubmitDecision = () => {
    const now = new Date().toLocaleString('en-US', {
      month: '2-digit',
      day: '2-digit',
      year: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
      hour12: true
    });

    if (actionChoice === 'approve') {
      setFdmStatus('approved');
      setProcessLog(prev => prev.map(entry => {
        if (entry.id === 4) return { ...entry, date: now, event: 'FDM approved recommended decision', actor: 'FDM Office', status: 'completed' };
        if (entry.id === 5) return { ...entry, date: now, event: 'Final Ruling Report generated by system', actor: 'System', status: 'completed' };
        if (entry.id === 6) return { ...entry, date: now, event: 'Final Ruling served to external parties', actor: 'System', status: 'completed' };
        return entry;
      }));
    } else {
      setFdmStatus('rejected');
      setProcessLog(prev => prev.map(entry => {
        if (entry.id === 4) return { ...entry, date: now, event: 'FDM rejected recommended decision', actor: 'FDM Office', status: 'completed' };
        if (entry.id === 5) return { ...entry, date: now, event: 'FDM uploaded own Final Ruling', actor: 'FDM Office', status: 'completed' };
        if (entry.id === 6) return { ...entry, date: now, event: 'Final Ruling served to external parties', actor: 'System', status: 'completed' };
        return entry;
      }));
    }
    setIsSubmitted(true);
    toast.success('Final Administrative Decision recorded');
  };

  const canSubmit = () => {
    if (actionChoice === 'approve') {
      return isRulingGenerated;
    }
    if (actionChoice === 'disagree') {
      return uploadedFile && rejectionJustification.trim().length > 0;
    }
    return false;
  };

  const getStatusBadge = () => {
    switch (fdmStatus) {
      case 'approved':
        return <Badge className="bg-green-100 text-green-800 font-fluent">Approved</Badge>;
      case 'rejected':
        return <Badge className="bg-orange-100 text-orange-800 font-fluent">Rejected</Badge>;
      default:
        return <Badge className="bg-yellow-100 text-yellow-800 font-fluent">FDM Pending</Badge>;
    }
  };

  const getDeadlineChip = () => {
    if (caseData.daysRemaining <= 0) {
      return <Badge className="bg-red-100 text-red-800 font-fluent">Overdue</Badge>;
    } else if (caseData.daysRemaining <= 3) {
      return <Badge className="bg-yellow-100 text-yellow-800 font-fluent">Due Soon</Badge>;
    }
    return <Badge className="bg-blue-100 text-blue-800 font-fluent">FDM Pending</Badge>;
  };

  return (
    <div className="min-h-screen bg-gray-100">
      <Header />
      
      <main className="container mx-auto px-6 py-6">
        {/* Breadcrumb */}
        <div className="flex items-center text-sm text-muted-foreground mb-4 font-fluent">
          <span 
            className="hover:text-primary cursor-pointer"
            onClick={() => navigate('/portal')}
          >
            Cases
          </span>
          <ChevronRight className="h-4 w-4 mx-2" />
          <span className="hover:text-primary cursor-pointer">
            {caseData.caseNumber}
          </span>
          <ChevronRight className="h-4 w-4 mx-2" />
          <span className="text-foreground font-medium">Final Decision</span>
        </div>

        {/* Page Title */}
        <h1 className="text-2xl font-semibold text-[#1a365d] font-fluent mb-6">
          Final Decision
        </h1>

        {/* Top Summary Strip */}
        <Card className="mb-6 border border-gray-200 shadow-sm">
          <CardContent className="p-4">
            <div className="flex items-center justify-end gap-8">
              <div className="text-right">
                <div className="text-xs text-muted-foreground font-fluent">Case ID</div>
                <div className="font-medium font-fluent">{caseData.caseNumber}</div>
              </div>
              <div className="text-right">
                <div className="text-xs text-muted-foreground font-fluent">Case Type</div>
                <div className="font-medium font-fluent">{caseData.caseType}</div>
              </div>
              <div className="text-right">
                <div className="text-xs text-muted-foreground font-fluent">Primary Party</div>
                <div className="font-medium font-fluent">{caseData.primaryParty}</div>
              </div>
              <div className="text-right">
                <div className="text-xs text-muted-foreground font-fluent">FDM Deadline</div>
                <div className="flex items-center gap-2">
                  <span className="font-medium font-fluent">{caseData.deadline}</span>
                  {getDeadlineChip()}
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Tabs */}
        <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
          <TabsList className="bg-white border border-gray-200 mb-4">
            <TabsTrigger 
              value="recommended" 
              className="font-fluent data-[state=active]:bg-blue-600 data-[state=active]:text-white"
            >
              Recommended Documents
            </TabsTrigger>
            <TabsTrigger 
              value="final" 
              className="font-fluent data-[state=active]:bg-blue-600 data-[state=active]:text-white"
            >
              Final Decision
            </TabsTrigger>
            <TabsTrigger 
              value="process" 
              className="font-fluent data-[state=active]:bg-blue-600 data-[state=active]:text-white"
            >
              Process Log
            </TabsTrigger>
          </TabsList>

          {/* Tab 1: Recommended Documents */}
          <TabsContent value="recommended">
            <Card className="border border-gray-200 shadow-sm">
              <CardHeader className="border-b border-gray-200 bg-gray-50">
                <CardTitle className="text-lg font-fluent text-[#1a365d]">
                  Recommended Documents
                </CardTitle>
              </CardHeader>
              <CardContent className="p-4">
                <div className="space-y-3">
                  {recommendedDocuments.map((doc) => (
                    <div 
                      key={doc.id}
                      className="flex items-center justify-between p-3 bg-gray-50 rounded-lg border border-gray-200"
                    >
                      <div className="flex items-center gap-3">
                        <FileText className="h-5 w-5 text-blue-600" />
                        <div>
                          <div className="font-medium font-fluent">{doc.name}</div>
                          <div className="text-xs text-muted-foreground font-fluent">
                            {doc.type} • {doc.uploadedBy} • {doc.date}
                          </div>
                        </div>
                      </div>
                      <Button variant="ghost" size="sm">
                        <Download className="h-4 w-4 text-blue-600" />
                      </Button>
                    </div>
                  ))}
                </div>

                {/* Info Banner */}
                <Alert className="mt-6 bg-blue-50 border-blue-200">
                  <Info className="h-4 w-4 text-blue-600" />
                  <AlertDescription className="font-fluent text-blue-800">
                    This recommended decision has triggered the Final Decision Maker workflow. Please proceed to Final Decision tab.
                  </AlertDescription>
                </Alert>
              </CardContent>
            </Card>
          </TabsContent>

          {/* Tab 2: Final Decision */}
          <TabsContent value="final">
            {isSubmitted ? (
              <Alert className="bg-green-50 border-green-200">
                <CheckCircle2 className="h-5 w-5 text-green-600" />
                <AlertDescription className="font-fluent text-green-800 text-base">
                  Final Administrative Decision recorded. The system has {actionChoice === 'approve' ? 'generated' : 'registered'} the Final Ruling Report and sent it to the appropriate external parties.
                </AlertDescription>
              </Alert>
            ) : (
              <div className="grid grid-cols-2 gap-6">
                {/* Left Card - Final Decision Summary */}
                <Card className="border border-gray-200 shadow-sm">
                  <CardHeader className="border-b border-gray-200 bg-gray-50">
                    <CardTitle className="text-lg font-fluent text-[#1a365d]">
                      Final Decision Summary
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="p-4 space-y-4">
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <label className="text-sm font-medium text-muted-foreground font-fluent">Case ID</label>
                        <div className="font-fluent mt-1">{caseData.caseNumber}</div>
                      </div>
                      <div>
                        <label className="text-sm font-medium text-muted-foreground font-fluent">Case Name</label>
                        <div className="font-fluent mt-1 text-sm">{caseData.caseName}</div>
                      </div>
                    </div>
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <label className="text-sm font-medium text-muted-foreground font-fluent">Department</label>
                        <div className="font-fluent mt-1">{caseData.department}</div>
                      </div>
                      <div>
                        <label className="text-sm font-medium text-muted-foreground font-fluent">Parties</label>
                        <div className="font-fluent mt-1 text-sm">{caseData.parties}</div>
                      </div>
                    </div>
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <label className="text-sm font-medium text-muted-foreground font-fluent">FDM Deadline</label>
                        <div className="flex items-center gap-2 mt-1">
                          <Calendar className="h-4 w-4 text-muted-foreground" />
                          <span className="font-fluent">{caseData.deadline}</span>
                        </div>
                      </div>
                      <div>
                        <label className="text-sm font-medium text-muted-foreground font-fluent">Days Remaining</label>
                        <div className="flex items-center gap-2 mt-1">
                          <Clock className="h-4 w-4 text-muted-foreground" />
                          <span className="font-fluent">{caseData.daysRemaining} days</span>
                        </div>
                      </div>
                    </div>
                    <div>
                      <label className="text-sm font-medium text-muted-foreground font-fluent">Status</label>
                      <div className="mt-1">
                        {getStatusBadge()}
                      </div>
                    </div>
                  </CardContent>
                </Card>

                {/* Right Card - Final Decision Maker Action */}
                <Card className="border border-gray-200 shadow-sm">
                  <CardHeader className="border-b border-gray-200 bg-gray-50">
                    <CardTitle className="text-lg font-fluent text-[#1a365d]">
                      Final Decision Maker Action
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="p-4 space-y-6">
                    {/* Action Choice */}
                    <div className="space-y-3">
                      <label className="text-sm font-medium text-muted-foreground font-fluent">Choose Your Action</label>
                      <div className="flex gap-3 justify-center">
                        <Button
                          variant={actionChoice === 'approve' ? 'default' : 'outline'}
                          className={`h-14 px-6 flex items-center justify-center gap-2 rounded-full ${
                            actionChoice === 'approve' ? 'bg-green-600 hover:bg-green-700' : 'border-2'
                          }`}
                          onClick={() => {
                            setActionChoice('approve');
                            setUploadedFile(null);
                            setRejectionJustification('');
                          }}
                        >
                          <CheckCircle2 className="h-5 w-5" />
                          <span className="font-fluent">Approve Recommended Decision</span>
                        </Button>
                        <Button
                          variant={actionChoice === 'disagree' ? 'default' : 'outline'}
                          className={`h-14 px-6 flex items-center justify-center gap-2 rounded-full ${
                            actionChoice === 'disagree' ? 'bg-orange-600 hover:bg-orange-700' : 'border-2'
                          }`}
                          onClick={() => {
                            setActionChoice('disagree');
                            setIsRulingGenerated(false);
                            setApprovalComments('');
                          }}
                        >
                          <XCircle className="h-5 w-5" />
                          <span className="font-fluent">Disagree / Upload Own Ruling</span>
                        </Button>
                      </div>
                    </div>

                    {/* Approve Section */}
                    {actionChoice === 'approve' && (
                      <div className="space-y-4 p-4 bg-green-50 rounded-lg border border-green-200">
                        <p className="text-sm font-fluent text-green-800">
                          Approving will automatically generate a Final Ruling Report based on the ALJ's recommendation.
                        </p>
                        <div>
                          <label className="text-sm font-medium text-muted-foreground font-fluent">
                            Optional comments to accompany your approval
                          </label>
                          <Textarea
                            value={approvalComments}
                            onChange={(e) => setApprovalComments(e.target.value)}
                            placeholder="Enter any additional comments..."
                            className="mt-2 font-fluent"
                            rows={3}
                          />
                        </div>
                        {!isRulingGenerated ? (
                          <Button 
                            className="w-full bg-green-600 hover:bg-green-700 font-fluent"
                            onClick={handleGenerateRuling}
                          >
                            Generate Final Ruling Report
                          </Button>
                        ) : (
                          <div className="space-y-3">
                            <div className="flex items-center justify-between p-3 bg-white rounded-lg border border-green-200">
                              <div className="flex items-center gap-3">
                                <FileText className="h-5 w-5 text-green-600" />
                                <div>
                                  <div className="font-medium font-fluent">Final Ruling Report</div>
                                  <div className="text-xs text-muted-foreground font-fluent">
                                    System Generated • Generated by FDM • {new Date().toLocaleDateString()}
                                  </div>
                                </div>
                              </div>
                              <Button variant="ghost" size="sm">
                                <Download className="h-4 w-4 text-green-600" />
                              </Button>
                            </div>
                          </div>
                        )}
                      </div>
                    )}

                    {/* Reject Section */}
                    {actionChoice === 'disagree' && (
                      <div className="space-y-4 p-4 bg-orange-50 rounded-lg border border-orange-200">
                        <div className="flex items-start gap-2">
                          <AlertTriangle className="h-5 w-5 text-orange-600 mt-0.5" />
                          <p className="text-sm font-fluent text-orange-800">
                            Upload your own final ruling PDF. This will replace the ALJ recommendation.
                          </p>
                        </div>

                        {/* File Upload Zone */}
                        <div className="border-2 border-dashed border-orange-300 rounded-lg p-6 text-center bg-white">
                          <input
                            type="file"
                            id="file-upload"
                            accept=".pdf"
                            className="hidden"
                            onChange={handleFileUpload}
                          />
                          {uploadedFile ? (
                            <div className="flex items-center justify-center gap-3">
                              <FileText className="h-8 w-8 text-orange-600" />
                              <div>
                                <div className="font-medium font-fluent">{uploadedFile.name}</div>
                                <div className="text-xs text-muted-foreground font-fluent">
                                  {(uploadedFile.size / 1024 / 1024).toFixed(2)} MB
                                </div>
                              </div>
                              <Button
                                variant="ghost"
                                size="sm"
                                onClick={() => setUploadedFile(null)}
                              >
                                <XCircle className="h-4 w-4 text-red-500" />
                              </Button>
                            </div>
                          ) : (
                            <label htmlFor="file-upload" className="cursor-pointer">
                              <Upload className="h-10 w-10 text-orange-400 mx-auto mb-2" />
                              <p className="text-sm font-fluent text-muted-foreground">
                                Drag and drop files here, or click to select
                              </p>
                              <p className="text-xs text-muted-foreground font-fluent mt-1">
                                PDF only, max 10 MB
                              </p>
                            </label>
                          )}
                        </div>

                        <div>
                          <label className="text-sm font-medium text-orange-800 font-fluent">
                            Explain why you are disagreeing with the ALJ's recommendation *
                          </label>
                          <Textarea
                            value={rejectionJustification}
                            onChange={(e) => setRejectionJustification(e.target.value)}
                            placeholder="Enter your justification..."
                            className="mt-2 font-fluent border-orange-200"
                            rows={4}
                            required
                          />
                        </div>

                        <Button 
                          className="w-full bg-orange-600 hover:bg-orange-700 font-fluent"
                          disabled={!uploadedFile}
                        >
                          Upload Final Ruling & Mark as Final
                        </Button>
                      </div>
                    )}

                    {/* Bottom Buttons */}
                    {actionChoice && (
                      <div className="flex justify-end gap-3 pt-4 border-t border-gray-200">
                        <Button 
                          variant="outline" 
                          className="font-fluent"
                          onClick={() => {
                            setActionChoice(null);
                            setApprovalComments('');
                            setRejectionJustification('');
                            setUploadedFile(null);
                            setIsRulingGenerated(false);
                          }}
                        >
                          Cancel
                        </Button>
                        <Button 
                          className="bg-blue-600 hover:bg-blue-700 font-fluent"
                          disabled={!canSubmit()}
                          onClick={handleSubmitDecision}
                        >
                          Submit Final Decision
                        </Button>
                      </div>
                    )}
                  </CardContent>
                </Card>
              </div>
            )}
          </TabsContent>

          {/* Tab 3: Process Log */}
          <TabsContent value="process">
            <Card className="border border-gray-200 shadow-sm">
              <CardHeader className="border-b border-gray-200 bg-gray-50">
                <CardTitle className="text-lg font-fluent text-[#1a365d]">
                  Process Log
                </CardTitle>
              </CardHeader>
              <CardContent className="p-6">
                <div className="relative">
                  {/* Timeline line */}
                  <div className="absolute left-4 top-0 bottom-0 w-0.5 bg-gray-200" />
                  
                  <div className="space-y-6">
                    {processLog.map((entry, index) => (
                      <div key={entry.id} className="relative flex gap-4">
                        {/* Timeline dot */}
                        <div className={`relative z-10 w-8 h-8 rounded-full flex items-center justify-center ${
                          entry.status === 'completed' 
                            ? 'bg-green-100' 
                            : 'bg-gray-100'
                        }`}>
                          {entry.status === 'completed' ? (
                            <CheckCircle2 className="h-5 w-5 text-green-600" />
                          ) : (
                            <Circle className="h-5 w-5 text-gray-400" />
                          )}
                        </div>
                        
                        {/* Content */}
                        <div className="flex-1 pb-6">
                          <div className="bg-white rounded-lg border border-gray-200 p-4">
                            <div className="font-medium font-fluent text-gray-900">
                              {entry.event}
                            </div>
                            {entry.actor && (
                              <div className="text-sm text-muted-foreground font-fluent mt-1">
                                By: {entry.actor}
                              </div>
                            )}
                            {entry.date ? (
                              <div className="text-xs text-muted-foreground font-fluent mt-2">
                                {entry.date}
                              </div>
                            ) : (
                              <div className="text-xs text-gray-400 font-fluent mt-2 italic">
                                Pending
                              </div>
                            )}
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </main>
    </div>
  );
};

export default FinalDecisionTest;
