import React, { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Header } from '@/components/shared/Header';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';
import { 
  ChevronRight, 
  FileText, 
  Download, 
  Upload, 
  Check, 
  AlertCircle,
  Clock,
  User,
  Calendar,
  CheckCircle2,
  XCircle,
  Info
} from 'lucide-react';
import { toast } from '@/hooks/use-toast';

const FinalDecisionDetail2: React.FC = () => {
  const navigate = useNavigate();
  const { id } = useParams();
  const [activeTab, setActiveTab] = useState('recommended');
  const [actionChoice, setActionChoice] = useState<'approve' | 'disagree' | null>(null);
  const [approvalComments, setApprovalComments] = useState('');
  const [rejectionJustification, setRejectionJustification] = useState('');
  const [uploadedFile, setUploadedFile] = useState<File | null>(null);
  const [isRulingGenerated, setIsRulingGenerated] = useState(false);
  const [isSubmitted, setIsSubmitted] = useState(false);

  // Mock case data
  const caseData = {
    id: id,
    caseNumber: 'DBE-EC-02025-004',
    caseName: 'Smith vs. Department of Natural Resources',
    caseType: 'Abandoned Well',
    department: 'Natural Resources',
    parties: 'John Smith vs. Department of Natural Resources',
    fdmDeadline: '12/15/2024',
    daysRemaining: 6,
    status: 'On Time',
    aljName: 'Hon. Sarah Johnson',
    recommendedDate: '11/25/2024',
    recommendationOutcome: 'Granted',
    summary: 'After careful review of all evidence and testimony presented during the hearing, the Administrative Law Judge recommends that the petition be granted. The petitioner has demonstrated sufficient cause for the relief requested, and the respondent has not provided adequate grounds for denial.'
  };

  const documents = [
    { name: 'Recommended Decision Report', type: 'System Generated', uploadedBy: 'System', date: '11/25/2024' },
  ];

  const activityLog = [
    { event: 'Recommended Decision generated by ALJ', timestamp: '11/25/2024 10:30 AM', user: 'Hon. Sarah Johnson' },
    { event: 'Recommended Report & Notification sent to FDM', timestamp: '11/25/2024 10:35 AM', user: 'System' },
    { event: 'FDM opened case', timestamp: '11/26/2024 9:00 AM', user: 'Current User' },
  ];

  const handleGenerateRuling = () => {
    setIsRulingGenerated(true);
    toast({
      title: "Final Ruling Report Generated",
      description: "The Final Ruling Report has been created based on the ALJ's recommendation.",
    });
  };

  const handleFileUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      if (file.type !== 'application/pdf') {
        toast({
          title: "Invalid file type",
          description: "Please upload a PDF file only.",
          variant: "destructive",
        });
        return;
      }
      if (file.size > 10 * 1024 * 1024) {
        toast({
          title: "File too large",
          description: "Please upload a file smaller than 10 MB.",
          variant: "destructive",
        });
        return;
      }
      setUploadedFile(file);
      toast({
        title: "File uploaded",
        description: `${file.name} has been uploaded successfully.`,
      });
    }
  };

  const handleSubmit = () => {
    if (actionChoice === 'approve' && isRulingGenerated) {
      setIsSubmitted(true);
      toast({
        title: "Final Decision Submitted",
        description: "The Final Administrative Decision has been recorded and sent to external parties.",
      });
    } else if (actionChoice === 'disagree' && uploadedFile && rejectionJustification) {
      setIsSubmitted(true);
      toast({
        title: "Final Decision Submitted",
        description: "Your Final Ruling has been uploaded and sent to external parties.",
      });
    }
  };

  const canSubmit = 
    (actionChoice === 'approve' && isRulingGenerated) ||
    (actionChoice === 'disagree' && uploadedFile && rejectionJustification.length > 0);

  return (
    <div className="min-h-screen bg-gray-100">
      <Header />
      
      <main className="container mx-auto px-6 py-6">
        {/* Breadcrumb */}
        <div className="flex items-center text-sm text-muted-foreground mb-4 font-fluent">
          <span 
            className="hover:text-primary cursor-pointer"
            onClick={() => navigate('/portal')}
          >
            Dashboard
          </span>
          <ChevronRight className="h-4 w-4 mx-2" />
          <span 
            className="hover:text-primary cursor-pointer"
            onClick={() => navigate('/fdm2')}
          >
            Final Decisions
          </span>
          <ChevronRight className="h-4 w-4 mx-2" />
          <span className="text-foreground font-medium">{caseData.caseNumber}</span>
        </div>

        {/* Top Band */}
        <div className="bg-[#1a365d] text-white rounded-lg p-4 mb-6">
          <div className="flex items-center justify-between">
            <h1 className="text-xl font-semibold font-fluent">
              Final Decision – {caseData.caseName}
            </h1>
            <div className="flex items-center gap-4">
              <div className="text-right">
                <div className="text-sm opacity-80">Case: {caseData.caseNumber}</div>
                <div className="text-sm opacity-80">Type: {caseData.caseType}</div>
              </div>
              <div className="border-l border-white/30 pl-4">
                <div className="text-sm opacity-80">FDM Deadline: {caseData.fdmDeadline}</div>
                <Badge className={`mt-1 ${caseData.daysRemaining > 5 ? 'bg-green-500' : caseData.daysRemaining > 2 ? 'bg-yellow-500' : 'bg-red-500'} text-white`}>
                  {caseData.status} ({caseData.daysRemaining} days remaining)
                </Badge>
              </div>
            </div>
          </div>
        </div>

        {/* Tabs */}
        <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
          <TabsList className="bg-white border border-gray-200 mb-4">
            <TabsTrigger 
              value="recommended" 
              className="font-fluent data-[state=active]:bg-blue-600 data-[state=active]:text-white"
            >
              Recommended Decision
            </TabsTrigger>
            <TabsTrigger 
              value="final" 
              className="font-fluent data-[state=active]:bg-blue-600 data-[state=active]:text-white"
            >
              Final Decision
            </TabsTrigger>
            <TabsTrigger 
              value="activity" 
              className="font-fluent data-[state=active]:bg-blue-600 data-[state=active]:text-white"
            >
              Activity Log
            </TabsTrigger>
          </TabsList>

          {/* Tab 1: Recommended Decision */}
          <TabsContent value="recommended">
            <div className="grid grid-cols-2 gap-6">
              <Card className="border border-gray-200 shadow-sm">
                <CardHeader>
                  <CardTitle className="font-fluent text-[#1a365d] flex items-center gap-2">
                    <User className="h-5 w-5" />
                    Recommended Decision Details
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="text-sm text-muted-foreground font-fluent">ALJ Name</label>
                      <p className="font-fluent font-medium">{caseData.aljName}</p>
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground font-fluent">Recommended Decision Date</label>
                      <p className="font-fluent font-medium">{caseData.recommendedDate}</p>
                    </div>
                  </div>
                  <div>
                    <label className="text-sm text-muted-foreground font-fluent">Summary</label>
                    <p className="font-fluent text-sm mt-1">{caseData.summary}</p>
                  </div>
                </CardContent>
              </Card>

              <Card className="border border-gray-200 shadow-sm">
                <CardHeader>
                  <CardTitle className="font-fluent text-[#1a365d] flex items-center gap-2">
                    <FileText className="h-5 w-5" />
                    Recommended Documents
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-3">
                    {documents.map((doc, index) => (
                      <div key={index} className="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
                        <div className="flex items-center gap-3">
                          <FileText className="h-5 w-5 text-blue-600" />
                          <div>
                            <p className="font-fluent font-medium">{doc.name}</p>
                            <p className="text-sm text-muted-foreground font-fluent">
                              {doc.type} • {doc.uploadedBy} • {doc.date}
                            </p>
                          </div>
                        </div>
                        <Button variant="ghost" size="sm">
                          <Download className="h-4 w-4" />
                        </Button>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            </div>

            <div className="mt-4 p-4 bg-blue-50 border border-blue-200 rounded-lg flex items-start gap-3">
              <Info className="h-5 w-5 text-blue-600 mt-0.5" />
              <p className="text-sm font-fluent text-blue-800">
                This recommended decision has been routed to you as Final Decision Maker. Approve it to generate a Final Ruling Report, or upload your own final ruling if you disagree.
              </p>
            </div>
          </TabsContent>

          {/* Tab 2: Final Decision */}
          <TabsContent value="final">
            {isSubmitted ? (
              <Card className="border border-green-200 bg-green-50 shadow-sm">
                <CardContent className="p-8 text-center">
                  <CheckCircle2 className="h-16 w-16 text-green-600 mx-auto mb-4" />
                  <h2 className="text-xl font-semibold font-fluent text-green-800 mb-2">
                    Final Administrative Decision Recorded
                  </h2>
                  <p className="font-fluent text-green-700">
                    The system has {actionChoice === 'approve' ? 'generated' : 'registered'} the Final Ruling Report and sent it to the appropriate external parties.
                  </p>
                </CardContent>
              </Card>
            ) : (
              <div className="grid grid-cols-2 gap-6">
                <Card className="border border-gray-200 shadow-sm">
                  <CardHeader>
                    <CardTitle className="font-fluent text-[#1a365d]">Final Decision Summary</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <label className="text-sm text-muted-foreground font-fluent">Case ID</label>
                        <p className="font-fluent font-medium">{caseData.caseNumber}</p>
                      </div>
                      <div>
                        <label className="text-sm text-muted-foreground font-fluent">Case Name</label>
                        <p className="font-fluent font-medium">{caseData.caseName}</p>
                      </div>
                      <div>
                        <label className="text-sm text-muted-foreground font-fluent">Department</label>
                        <p className="font-fluent font-medium">{caseData.department}</p>
                      </div>
                      <div>
                        <label className="text-sm text-muted-foreground font-fluent">Parties</label>
                        <p className="font-fluent font-medium">{caseData.parties}</p>
                      </div>
                    </div>
                    <div className="pt-4 border-t">
                      <div className="flex items-center justify-between">
                        <div>
                          <label className="text-sm text-muted-foreground font-fluent">FDM Deadline</label>
                          <p className="font-fluent font-medium">{caseData.fdmDeadline}</p>
                        </div>
                        <div>
                          <label className="text-sm text-muted-foreground font-fluent">Days Remaining</label>
                          <p className="font-fluent font-medium">{caseData.daysRemaining} days</p>
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </Card>

                <Card className="border border-gray-200 shadow-sm">
                  <CardHeader className="flex flex-row items-center justify-between">
                    <CardTitle className="font-fluent text-[#1a365d]">Final Decision Maker Action</CardTitle>
                    <Badge className="bg-yellow-100 text-yellow-800 font-fluent">
                      FDM Pending
                    </Badge>
                  </CardHeader>
                  <CardContent className="space-y-6">
                    {/* Action Choice */}
                    <div className="space-y-3">
                      <label className="text-sm font-medium font-fluent">Select your action:</label>
                      <div className="grid grid-cols-2 gap-3">
                        <Button
                          variant={actionChoice === 'approve' ? 'default' : 'outline'}
                          className={`h-auto py-4 flex flex-col items-center gap-2 ${actionChoice === 'approve' ? 'bg-green-600 hover:bg-green-700' : ''}`}
                          onClick={() => setActionChoice('approve')}
                        >
                          <Check className="h-6 w-6" />
                          <span className="font-fluent">Approve Recommended Decision</span>
                        </Button>
                        <Button
                          variant={actionChoice === 'disagree' ? 'default' : 'outline'}
                          className={`h-auto py-4 flex flex-col items-center gap-2 ${actionChoice === 'disagree' ? 'bg-red-600 hover:bg-red-700' : ''}`}
                          onClick={() => setActionChoice('disagree')}
                        >
                          <XCircle className="h-6 w-6" />
                          <span className="font-fluent">Disagree / Upload Own Final Ruling</span>
                        </Button>
                      </div>
                    </div>

                    {/* Approve Section */}
                    {actionChoice === 'approve' && (
                      <div className="space-y-4 p-4 bg-green-50 rounded-lg border border-green-200">
                        <p className="text-sm font-fluent text-green-800">
                          Approving will automatically generate a Final Ruling Report based on the ALJ's recommendation.
                        </p>
                        <Textarea
                          placeholder="Optional comments to accompany your approval..."
                          className="font-fluent"
                          value={approvalComments}
                          onChange={(e) => setApprovalComments(e.target.value)}
                        />
                        {!isRulingGenerated ? (
                          <Button 
                            className="w-full bg-green-600 hover:bg-green-700"
                            onClick={handleGenerateRuling}
                          >
                            Generate Final Ruling Report
                          </Button>
                        ) : (
                          <div className="space-y-3">
                            <div className="flex items-center justify-between p-3 bg-white rounded-lg border">
                              <div className="flex items-center gap-3">
                                <FileText className="h-5 w-5 text-green-600" />
                                <div>
                                  <p className="font-fluent font-medium">Final Ruling Report</p>
                                  <p className="text-sm text-muted-foreground font-fluent">System Generated • Just now</p>
                                </div>
                              </div>
                              <Button variant="ghost" size="sm">
                                <Download className="h-4 w-4" />
                              </Button>
                            </div>
                            <Button className="w-full bg-blue-600 hover:bg-blue-700">
                              Sign & Send
                            </Button>
                          </div>
                        )}
                      </div>
                    )}

                    {/* Disagree Section */}
                    {actionChoice === 'disagree' && (
                      <div className="space-y-4 p-4 bg-red-50 rounded-lg border border-red-200">
                        <p className="text-sm font-fluent text-red-800">
                          Upload your own final ruling PDF. This will replace the ALJ's recommendation as the Final Administrative Decision.
                        </p>
                        <div className="border-2 border-dashed border-red-300 rounded-lg p-6 text-center">
                          <input
                            type="file"
                            accept=".pdf"
                            className="hidden"
                            id="file-upload"
                            onChange={handleFileUpload}
                          />
                          <label htmlFor="file-upload" className="cursor-pointer">
                            <Upload className="h-8 w-8 mx-auto text-red-400 mb-2" />
                            <p className="font-fluent text-sm text-red-700">
                              Drag and drop files here, or click to browse
                            </p>
                            <p className="text-xs text-red-500 mt-1">PDF only, max 10 MB</p>
                          </label>
                        </div>
                        {uploadedFile && (
                          <div className="flex items-center justify-between p-3 bg-white rounded-lg border">
                            <div className="flex items-center gap-3">
                              <FileText className="h-5 w-5 text-red-600" />
                              <div>
                                <p className="font-fluent font-medium">{uploadedFile.name}</p>
                                <p className="text-sm text-muted-foreground font-fluent">
                                  {(uploadedFile.size / 1024 / 1024).toFixed(2)} MB
                                </p>
                              </div>
                            </div>
                            <Button variant="ghost" size="sm" onClick={() => setUploadedFile(null)}>
                              <XCircle className="h-4 w-4" />
                            </Button>
                          </div>
                        )}
                        <div>
                          <label className="text-sm font-medium font-fluent text-red-800">
                            Required justification for rejecting the recommendation: *
                          </label>
                          <Textarea
                            placeholder="Explain why you are rejecting the ALJ's recommendation..."
                            className="font-fluent mt-2"
                            value={rejectionJustification}
                            onChange={(e) => setRejectionJustification(e.target.value)}
                            required
                          />
                        </div>
                        <Button 
                          className="w-full bg-red-600 hover:bg-red-700"
                          disabled={!uploadedFile || !rejectionJustification}
                        >
                          Upload Final Ruling & Mark as Final
                        </Button>
                      </div>
                    )}

                    {/* Submit Button */}
                    <div className="flex gap-3 pt-4 border-t">
                      <Button 
                        className="flex-1 bg-blue-600 hover:bg-blue-700"
                        disabled={!canSubmit}
                        onClick={handleSubmit}
                      >
                        Submit Final Decision
                      </Button>
                      <Button 
                        variant="outline" 
                        className="flex-1"
                        onClick={() => navigate('/fdm2')}
                      >
                        Cancel
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              </div>
            )}
          </TabsContent>

          {/* Tab 3: Activity Log */}
          <TabsContent value="activity">
            <Card className="border border-gray-200 shadow-sm">
              <CardHeader>
                <CardTitle className="font-fluent text-[#1a365d] flex items-center gap-2">
                  <Clock className="h-5 w-5" />
                  Activity Log
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  {activityLog.map((log, index) => (
                    <div key={index} className="flex items-start gap-4 p-4 bg-gray-50 rounded-lg">
                      <div className="w-3 h-3 bg-blue-600 rounded-full mt-1.5"></div>
                      <div className="flex-1">
                        <p className="font-fluent font-medium">{log.event}</p>
                        <div className="flex items-center gap-4 mt-1 text-sm text-muted-foreground">
                          <span className="flex items-center gap-1">
                            <Calendar className="h-3 w-3" />
                            {log.timestamp}
                          </span>
                          <span className="flex items-center gap-1">
                            <User className="h-3 w-3" />
                            {log.user}
                          </span>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </main>
    </div>
  );
};

export default FinalDecisionDetail2;
